### ISSUE TITLE
Investigate about payment solution

### ISSUE THREAD

**Issue by andriy-ilin** [andriy-ilin/test-ci-crna#19]
Look at such  payment method as LIQPAY:
- [ ] - find out fee per transaction
- [ ] - get private and public key for Ukrainer
- [ ] - check this repo https://github.com/liqpay/sdk-nodejs/blob/master/lib/liqpay.js
