### ISSUE TITLE
structure screens application

### ISSUE THREAD

**Issue by andriy-ilin** [andriy-ilin/test-ci-crna#23]
- [x] - make file with structure project (get screens structure from AppNavigator)
- [x] - describe all screens
- [x] - make and link screenshots
