### ISSUE TITLE
get data about region from api

### ISSUE THREAD

**Issue by andriy-ilin** [andriy-ilin/test-ci-crna#24]
- [x] connect api region {name} in filter component on RegionScreen
- [x] connect api region {name, imageUrl} about region in RegionContainer on RegionScreen
- [x] connect api region {name}  in filter component on VideoScreen
